wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 50
max_length:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1730690361.842139
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.16.3
      6: 4.38.1
      8:
      - 1
      - 5
      13: linux-x86_64
