wandb_version: 1

model:
  desc: null
  value: "MLP(\n  (fc1): Linear(in_features=110250, out_features=256, bias=True)\n\
    \  (fc2): Linear(in_features=256, out_features=10, bias=True)\n)"
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1730831865.991201
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.16.3
      6: 4.38.1
      8:
      - 1
      - 5
      13: linux-x86_64
